-- Migration: Insert Sample Warehouse Types with All Fields
-- Date: 2025-01-28
-- Description: Creates sample warehouse types with complete data including address fields

-- Insert sample warehouse types
INSERT INTO warehouse_types (
  code,
  name,
  description,
  storage_type,
  temperature_range,
  special_requirements,
  handling_equipment,
  is_active,
  address_line_1,
  address_line_2,
  city,
  state,
  country,
  postal_code,
  contact_person,
  phone,
  email,
  created_at,
  updated_at
) VALUES
(
  'WH-AMB-001',
  'Ambient Warehouse',
  'Standard ambient temperature warehouse for dry goods and non-perishable items. Suitable for electronics, clothing, and general merchandise.',
  'AMBIENT',
  '15°C - 25°C',
  'Dry storage only. No special handling requirements.',
  'Forklifts, Pallet Jacks, Conveyor Belts',
  true,
  '1234 Industrial Park Drive',
  'Building A, Suite 100',
  'Atlanta',
  'Georgia',
  'United States',
  '30309',
  'John Smith',
  '+1-404-555-0101',
  'warehouse1@company.com',
  NOW(),
  NOW()
),
(
  'WH-REF-001',
  'Refrigerated Warehouse',
  'Temperature-controlled warehouse for perishable food items requiring refrigeration. Maintains products at optimal temperature.',
  'REFRIGERATED',
  '2°C - 8°C',
  'Temperature monitoring required. Backup power system in place.',
  'Refrigerated Trucks, Cold Storage Units, Temperature-Controlled Forklifts',
  true,
  '5678 Cold Storage Boulevard',
  'Unit 200',
  'Chicago',
  'Illinois',
  'United States',
  '60601',
  'Sarah Johnson',
  '+1-312-555-0202',
  'coldstorage@company.com',
  NOW(),
  NOW()
),
(
  'WH-FRZ-001',
  'Frozen Warehouse',
  'Deep freeze warehouse for frozen food products and items requiring sub-zero temperatures.',
  'FROZEN',
  '-20°C - -18°C',
  'Continuous temperature monitoring. Emergency backup generators required.',
  'Freezer Units, Cryogenic Handling Equipment, Insulated Vehicles',
  true,
  '9012 Frost Way',
  'Cold Zone 3',
  'Minneapolis',
  'Minnesota',
  'United States',
  '55401',
  'Michael Brown',
  '+1-612-555-0303',
  'frozenwarehouse@company.com',
  NOW(),
  NOW()
),
(
  'WH-HAZ-001',
  'Hazmat Warehouse',
  'Specialized warehouse for handling hazardous materials. Compliant with all safety regulations.',
  'HAZMAT',
  'Ambient',
  'Hazmat certified staff required. Fire suppression system. Emergency response protocols in place.',
  'Hazmat Suits, Chemical Storage Containers, Safety Equipment, Spill Kits',
  true,
  '3456 Safety Lane',
  'Hazmat Facility B',
  'Houston',
  'Texas',
  'United States',
  '77001',
  'Emily Davis',
  '+1-713-555-0404',
  'hazmat@company.com',
  NOW(),
  NOW()
),
(
  'WH-AMB-002',
  'Distribution Center',
  'Large-scale distribution warehouse for high-volume inventory management and order fulfillment.',
  'AMBIENT',
  '18°C - 22°C',
  'High-security access control. Automated inventory systems.',
  'Automated Conveyor Systems, High-Rack Storage, Picking Robots, Loading Docks',
  true,
  '7890 Distribution Parkway',
  'DC Building 1',
  'Dallas',
  'Texas',
  'United States',
  '75201',
  'Robert Wilson',
  '+1-214-555-0505',
  'distribution@company.com',
  NOW(),
  NOW()
),
(
  'WH-REF-002',
  'Pharmaceutical Storage',
  'Temperature-controlled warehouse for pharmaceutical products requiring strict temperature and humidity control.',
  'REFRIGERATED',
  '2°C - 8°C',
  'FDA compliant. Temperature logging required. Humidity control: 45-65% RH.',
  'Pharmaceutical Refrigerators, Temperature Loggers, Humidity Monitors, Secure Storage',
  true,
  '2468 Pharma Drive',
  'Pharma Building A',
  'Boston',
  'Massachusetts',
  'United States',
  '02101',
  'Dr. Lisa Anderson',
  '+1-617-555-0606',
  'pharmastorage@company.com',
  NOW(),
  NOW()
),
(
  'WH-AMB-003',
  'Cross-Dock Facility',
  'Fast-moving warehouse for cross-docking operations with minimal storage time.',
  'AMBIENT',
  '15°C - 25°C',
  '24/7 operations. Quick turnaround required.',
  'High-Speed Conveyors, Dock Levelers, Yard Trucks, Sortation Systems',
  true,
  '1357 Cross Dock Road',
  'Gate 5',
  'Los Angeles',
  'California',
  'United States',
  '90001',
  'Carlos Martinez',
  '+1-213-555-0707',
  'crossdock@company.com',
  NOW(),
  NOW()
),
(
  'WH-HAZ-002',
  'Chemical Storage',
  'Specialized facility for chemical storage with proper ventilation and safety measures.',
  'HAZMAT',
  '15°C - 25°C',
  'Chemical compatibility matrix required. Ventilation system. Chemical spill response team.',
  'Chemical Storage Cabinets, Ventilation Systems, Personal Protective Equipment, Emergency Showers',
  true,
  '8642 Chemical Avenue',
  'Chemical Bay 4',
  'Detroit',
  'Michigan',
  'United States',
  '48201',
  'James Taylor',
  '+1-313-555-0808',
  'chemicalstorage@company.com',
  NOW(),
  NOW()
)
ON CONFLICT (code) DO NOTHING;

-- Display inserted records
SELECT 
  id,
  code,
  name,
  storage_type,
  city,
  state,
  country,
  is_active,
  created_at
FROM warehouse_types
WHERE code IN (
  'WH-AMB-001',
  'WH-REF-001',
  'WH-FRZ-001',
  'WH-HAZ-001',
  'WH-AMB-002',
  'WH-REF-002',
  'WH-AMB-003',
  'WH-HAZ-002'
)
ORDER BY code;

