-- Insert initial depreciation methods data
-- Common depreciation methods used in asset accounting

-- Straight Line Depreciation Methods
INSERT INTO depreciation_methods (
  code, name, description, calculation_type, base_value_type,
  depreciation_rate, useful_life_years, residual_value_percent,
  allow_partial_year, prorata_basis, switch_method_allowed,
  company_code_id, applicable_to_asset_class, is_active, is_default
) VALUES
(
  'STL-001',
  'Straight Line - Standard',
  'Standard straight-line depreciation method with equal annual depreciation',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  10,
  0,
  true,
  'DAYS',
  false,
  NULL,
  NULL,
  true,
  true
),
(
  'STL-002',
  'Straight Line - With Residual',
  'Straight-line method accounting for residual value at end of useful life',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  5,
  10,
  true,
  'DAYS',
  false,
  NULL,
  NULL,
  true,
  false
),
(
  'STL-003',
  'Straight Line - Full Year',
  'Straight-line depreciation calculated on full year basis only',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  7,
  0,
  false,
  'FULL_YEAR',
  false,
  NULL,
  NULL,
  true,
  false
),
(
  'DBL-001',
  'Double Declining Balance',
  'Accelerated depreciation method using 200% of straight-line rate',
  'DECLINING_BALANCE',
  'BOOK_VALUE',
  20,
  5,
  0,
  true,
  'DAYS',
  true,
  NULL,
  NULL,
  true,
  false
),
(
  'DBL-002',
  '150% Declining Balance',
  'Moderate accelerated depreciation using 150% of straight-line rate',
  'DECLINING_BALANCE',
  'BOOK_VALUE',
  15,
  8,
  5,
  true,
  'DAYS',
  true,
  NULL,
  NULL,
  true,
  false
),
(
  'DBL-003',
  'Custom Declining Balance',
  'Custom declining balance method with configurable rate',
  'DECLINING_BALANCE',
  'BOOK_VALUE',
  25,
  6,
  0,
  true,
  'MONTHS',
  false,
  NULL,
  NULL,
  true,
  false
),
(
  'UOP-001',
  'Units of Production',
  'Depreciation based on actual usage or production output',
  'UNITS_OF_PRODUCTION',
  'ACQUISITION_VALUE',
  NULL,
  10,
  5,
  true,
  'DAYS',
  false,
  NULL,
  NULL,
  true,
  false
),
(
  'SYD-001',
  'Sum of Years Digits',
  'Accelerated depreciation using sum of years digits formula',
  'SUM_OF_YEARS',
  'ACQUISITION_VALUE',
  NULL,
  5,
  0,
  true,
  'DAYS',
  true,
  NULL,
  NULL,
  true,
  false
),
(
  'SYD-002',
  'Sum of Years Digits - Extended',
  'Sum of years digits method for longer-lived assets',
  'SUM_OF_YEARS',
  'ACQUISITION_VALUE',
  NULL,
  10,
  10,
  true,
  'DAYS',
  true,
  NULL,
  NULL,
  true,
  false
),
(
  'SPC-001',
  'IT Equipment - 3 Year',
  'Standard 3-year depreciation for IT equipment and computers',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  3,
  0,
  true,
  'DAYS',
  false,
  NULL,
  'IT_EQUIPMENT',
  true,
  false
),
(
  'SPC-002',
  'Vehicles - 5 Year',
  '5-year depreciation method for vehicles and transportation assets',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  5,
  10,
  true,
  'DAYS',
  false,
  NULL,
  'VEHICLES',
  true,
  false
),
(
  'SPC-003',
  'Buildings - 30 Year',
  'Long-term depreciation for buildings and real estate',
  'STRAIGHT_LINE',
  'ACQUISITION_VALUE',
  NULL,
  30,
  0,
  true,
  'DAYS',
  false,
  NULL,
  'BUILDINGS',
  true,
  false
),
(
  'SPC-004',
  'Machinery - Accelerated',
  'Accelerated depreciation for manufacturing machinery',
  'DECLINING_BALANCE',
  'BOOK_VALUE',
  20,
  8,
  0,
  true,
  'DAYS',
  true,
  NULL,
  'MACHINERY',
  true,
  false
);
