import pkg from 'pg';
const { Pool } = pkg;

interface PurchaseRequisitionData {
  requisitionNumber: string;
  requestorName: string;
  plantId: number;
  materialCode: string;
  quantity: number;
  estimatedPrice: number;
  requiredDate: Date;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  businessJustification: string;
}

export class PurchaseRequisitionService {
  private pool: Pool;

  constructor(pool: Pool) {
    this.pool = pool;
  }

  /**
   * Auto-create purchase requisitions from MRP requirements
   * This implements the PR automation from your diagram
   */
  async autoCreatePurchaseRequisition(
    materialCode: string,
    plantId: number,
    requiredQuantity: number,
    requiredDate: Date,
    sourceDocument: string = 'MRP_RUN',
    requestorName: string = 'MRP System'
  ): Promise<{ success: boolean; prNumber?: string; prId?: number }> {
    try {
      // Check if material requires external procurement
      const materialQuery = `
        SELECT 
          material_code,
          description,
          procurement_type,
          base_unit_of_measure,
          purchasing_group
        FROM materials 
        WHERE material_code = $1 AND procurement_type IN ('EXTERNAL', 'BOTH')
      `;

      const materialResult = await this.pool.query(materialQuery, [materialCode]);
      
      if (materialResult.rows.length === 0) {
        console.log(`Material ${materialCode} not suitable for external procurement`);
        return { success: false };
      }

      const material = materialResult.rows[0];
      
      // Get vendor information for material
      const vendorQuery = `
        SELECT 
          vendor_code,
          price,
          currency,
          minimum_order_quantity
        FROM material_vendor_info 
        WHERE material_code = $1 
        ORDER BY is_preferred DESC, price ASC
        LIMIT 1
      `;

      const vendorResult = await this.pool.query(vendorQuery, [materialCode]);
      
      let estimatedPrice = 100; // Default price
      let vendorCode = 'VENDOR_001'; // Default vendor
      
      if (vendorResult.rows.length > 0) {
        estimatedPrice = parseFloat(vendorResult.rows[0].price);
        vendorCode = vendorResult.rows[0].vendor_code;
      }

      // Generate PR number
      const prNumber = `PR-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;
      
      // Create purchase requisition header
      const prHeaderQuery = `
        INSERT INTO purchase_requisitions (
          requisition_number,
          requestor_name,
          request_date,
          required_date,
          plant_id,
          priority,
          status,
          approval_status,
          business_justification,
          source_document,
          created_by
        ) VALUES ($1, $2, CURRENT_DATE, $3, $4, 'HIGH', 'OPEN', 'PENDING', $5, $6, 'MRP_SYSTEM')
        RETURNING id
      `;

      const justification = `Auto-generated by MRP for material shortage. Required quantity: ${requiredQuantity} ${material.base_unit_of_measure}`;
      
      const prHeaderResult = await this.pool.query(prHeaderQuery, [
        prNumber,
        requestorName,
        requiredDate,
        plantId,
        justification,
        sourceDocument
      ]);

      const prId = prHeaderResult.rows[0].id;

      // Create purchase requisition line item
      const prItemQuery = `
        INSERT INTO purchase_requisition_items (
          pr_id,
          material_code,
          description,
          quantity,
          unit_of_measure,
          estimated_price,
          total_value,
          delivery_date,
          preferred_vendor
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `;

      const totalValue = requiredQuantity * estimatedPrice;
      
      await this.pool.query(prItemQuery, [
        prId,
        materialCode,
        material.description,
        requiredQuantity,
        material.base_unit_of_measure,
        estimatedPrice,
        totalValue,
        requiredDate,
        vendorCode
      ]);

      // Update MRP requirement status if applicable
      await this.updateMRPRequirementStatus(materialCode, plantId, 'PR_CREATED');

      return { 
        success: true, 
        prNumber,
        prId 
      };
    } catch (error) {
      console.error('Error auto-creating purchase requisition:', error);
      throw error;
    }
  }

  /**
   * Batch create purchase requisitions for multiple materials
   */
  async batchCreatePurchaseRequisitions(
    requirements: Array<{
      materialCode: string;
      plantId: number;
      requiredQuantity: number;
      requiredDate: Date;
    }>,
    requestorName: string = 'MRP System'
  ): Promise<{ created: number; failed: number; requisitions: any[] }> {
    let created = 0;
    let failed = 0;
    const requisitions = [];

    for (const req of requirements) {
      try {
        const result = await this.autoCreatePurchaseRequisition(
          req.materialCode,
          req.plantId,
          req.requiredQuantity,
          req.requiredDate,
          'MRP_BATCH',
          requestorName
        );

        if (result.success) {
          created++;
          requisitions.push({
            prNumber: result.prNumber,
            materialCode: req.materialCode,
            quantity: req.requiredQuantity
          });
        } else {
          failed++;
        }
      } catch (error) {
        failed++;
        console.error(`Failed to create PR for material ${req.materialCode}:`, error);
      }
    }

    return { created, failed, requisitions };
  }

  /**
   * Convert purchase requisition to purchase order
   */
  async convertToPurchaseOrder(
    prId: number,
    vendorCode: string,
    approvedBy: string
  ): Promise<{ success: boolean; poNumber?: string; poId?: number }> {
    try {
      // Get PR details
      const prQuery = `
        SELECT 
          pr.requisition_number,
          pr.plant_id,
          pri.material_code,
          pri.quantity,
          pri.estimated_price,
          pri.delivery_date,
          pri.description
        FROM purchase_requisitions pr
        JOIN purchase_requisition_items pri ON pr.id = pri.pr_id
        WHERE pr.id = $1 AND pr.approval_status = 'APPROVED'
      `;

      const prResult = await this.pool.query(prQuery, [prId]);
      
      if (prResult.rows.length === 0) {
        return { success: false };
      }

      const prData = prResult.rows[0];
      const poNumber = `PO-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;

      // Create purchase order header
      const poHeaderQuery = `
        INSERT INTO purchase_orders (
          order_number,
          vendor_code,
          plant_id,
          order_date,
          delivery_date,
          status,
          created_by,
          source_pr_id
        ) VALUES ($1, $2, $3, CURRENT_DATE, $4, 'OPEN', $5, $6)
        RETURNING id
      `;

      const poHeaderResult = await this.pool.query(poHeaderQuery, [
        poNumber,
        vendorCode,
        prData.plant_id,
        prData.delivery_date,
        approvedBy,
        prId
      ]);

      const poId = poHeaderResult.rows[0].id;

      // Create purchase order line items
      for (const item of prResult.rows) {
        await this.pool.query(`
          INSERT INTO purchase_order_items (
            po_id,
            material_code,
            description,
            quantity,
            unit_price,
            total_amount,
            delivery_date
          ) VALUES ($1, $2, $3, $4, $5, $6, $7)
        `, [
          poId,
          item.material_code,
          item.description,
          item.quantity,
          item.estimated_price,
          item.quantity * item.estimated_price,
          item.delivery_date
        ]);
      }

      // Update PR status
      await this.pool.query(
        'UPDATE purchase_requisitions SET status = $1 WHERE id = $2',
        ['CONVERTED', prId]
      );

      return { 
        success: true, 
        poNumber,
        poId 
      };
    } catch (error) {
      console.error('Error converting PR to PO:', error);
      throw error;
    }
  }

  /**
   * Approve purchase requisition
   */
  async approvePurchaseRequisition(
    prId: number,
    approvedBy: string,
    comments?: string
  ): Promise<{ success: boolean; message?: string }> {
    try {
      // Update approval status
      await this.pool.query(`
        UPDATE purchase_requisitions 
        SET 
          approval_status = 'APPROVED',
          approved_by = $1,
          approval_date = CURRENT_TIMESTAMP,
          approval_comments = $2
        WHERE id = $3 AND approval_status = 'PENDING'
      `, [approvedBy, comments, prId]);

      // Log approval
      await this.pool.query(`
        INSERT INTO purchase_requisition_approvals (
          pr_id,
          approver_name,
          approval_date,
          approval_status,
          comments
        ) VALUES ($1, $2, CURRENT_TIMESTAMP, 'APPROVED', $3)
      `, [prId, approvedBy, comments]);

      return { success: true, message: 'Purchase requisition approved successfully' };
    } catch (error) {
      console.error('Error approving purchase requisition:', error);
      throw error;
    }
  }

  /**
   * Get purchase requisition dashboard
   */
  async getPurchaseRequisitionDashboard(plantId?: number): Promise<any> {
    try {
      const baseWhereClause = plantId ? 'WHERE plant_id = $1' : '';
      const params = plantId ? [plantId] : [];

      // PR statistics
      const statsQuery = `
        SELECT 
          COUNT(*) as total_prs,
          COUNT(CASE WHEN approval_status = 'PENDING' THEN 1 END) as pending_approval,
          COUNT(CASE WHEN approval_status = 'APPROVED' THEN 1 END) as approved_prs,
          COUNT(CASE WHEN status = 'OPEN' THEN 1 END) as open_prs,
          COUNT(CASE WHEN status = 'CONVERTED' THEN 1 END) as converted_prs,
          SUM(CASE WHEN approval_status = 'APPROVED' THEN 
            (SELECT SUM(total_value) FROM purchase_requisition_items WHERE pr_id = purchase_requisitions.id)
          END) as approved_value
        FROM purchase_requisitions 
        ${baseWhereClause}
      `;

      const statsResult = await this.pool.query(statsQuery, params);

      // Urgent PRs
      const urgentQuery = `
        SELECT 
          requisition_number,
          requestor_name,
          required_date,
          priority,
          approval_status
        FROM purchase_requisitions 
        WHERE priority = 'URGENT' AND status = 'OPEN'
        ${plantId ? 'AND plant_id = $1' : ''}
        ORDER BY required_date ASC
        LIMIT 5
      `;

      const urgentResult = await this.pool.query(urgentQuery, params);

      // Recent PRs
      const recentQuery = `
        SELECT 
          requisition_number,
          requestor_name,
          request_date,
          approval_status,
          status
        FROM purchase_requisitions 
        ${baseWhereClause}
        ORDER BY request_date DESC
        LIMIT 10
      `;

      const recentResult = await this.pool.query(recentQuery, params);

      const stats = statsResult.rows[0] || {};

      return {
        totalPRs: parseInt(stats.total_prs || '0'),
        pendingApproval: parseInt(stats.pending_approval || '0'),
        approvedPRs: parseInt(stats.approved_prs || '0'),
        openPRs: parseInt(stats.open_prs || '0'),
        convertedPRs: parseInt(stats.converted_prs || '0'),
        approvedValue: parseFloat(stats.approved_value || '0'),
        urgentPRs: urgentResult.rows,
        recentPRs: recentResult.rows
      };
    } catch (error) {
      console.error('Error fetching PR dashboard:', error);
      throw error;
    }
  }

  /**
   * Update MRP requirement status
   */
  private async updateMRPRequirementStatus(
    materialCode: string,
    plantId: number,
    status: string
  ): Promise<void> {
    try {
      await this.pool.query(`
        UPDATE mrp_requirements 
        SET 
          procurement_status = $1,
          last_updated = CURRENT_TIMESTAMP
        WHERE material_code = $2 AND plant_id = $3
      `, [status, materialCode, plantId]);
    } catch (error) {
      console.error('Error updating MRP requirement status:', error);
    }
  }

  /**
   * Process vendor quotations for PR
   */
  async processVendorQuotations(
    prId: number,
    quotations: Array<{
      vendorCode: string;
      quotedPrice: number;
      deliveryDate: Date;
      validUntil: Date;
    }>
  ): Promise<{ success: boolean; recommendedVendor?: string }> {
    try {
      let bestVendor = quotations[0];
      let bestScore = 0;

      // Evaluate quotations based on price, delivery time, and vendor rating
      for (const quotation of quotations) {
        // Get vendor rating
        const vendorRatingQuery = `
          SELECT quality_rating, delivery_rating, price_rating
          FROM vendor_performance 
          WHERE vendor_code = $1
        `;
        
        const ratingResult = await this.pool.query(vendorRatingQuery, [quotation.vendorCode]);
        
        let qualityRating = 3; // Default rating
        let deliveryRating = 3;
        let priceRating = 3;
        
        if (ratingResult.rows.length > 0) {
          qualityRating = ratingResult.rows[0].quality_rating || 3;
          deliveryRating = ratingResult.rows[0].delivery_rating || 3;
          priceRating = ratingResult.rows[0].price_rating || 3;
        }

        // Calculate score (weighted average)
        const priceScore = (1 / quotation.quotedPrice) * 1000; // Inverse price
        const deliveryScore = deliveryRating * 20;
        const qualityScore = qualityRating * 20;
        
        const totalScore = (priceScore * 0.4) + (deliveryScore * 0.3) + (qualityScore * 0.3);
        
        if (totalScore > bestScore) {
          bestScore = totalScore;
          bestVendor = quotation;
        }

        // Store quotation
        await this.pool.query(`
          INSERT INTO vendor_quotations (
            pr_id,
            vendor_code,
            quoted_price,
            delivery_date,
            valid_until,
            evaluation_score
          ) VALUES ($1, $2, $3, $4, $5, $6)
        `, [prId, quotation.vendorCode, quotation.quotedPrice, quotation.deliveryDate, quotation.validUntil, totalScore]);
      }

      return { 
        success: true, 
        recommendedVendor: bestVendor.vendorCode 
      };
    } catch (error) {
      console.error('Error processing vendor quotations:', error);
      throw error;
    }
  }
}