import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { MapPin, Building, Truck, CreditCard, Copy, Edit, Check, Plus, Trash2 } from 'lucide-react';

interface AddressEntry {
  id: string;
  address_number?: string; // Auto-generated unique address number from database
  address_name: string;
  contact_person: string;
  company_name: string;
  address_line_1: string;
  address_line_2: string;
  city: string;
  state: string;
  country: string;
  postal_code: string;
  region: string;
  phone: string;
  email: string;
  is_primary: boolean;
  notes: string;
}

interface CustomerAddress {
  // Main address (sold-to)
  address: string;
  city: string;
  state: string;
  country: string;
  postal_code: string;
  phone: string;
  email: string;

  // Additional main address fields (optional)
  contact_person?: string;
  company_name?: string;
  address_line_2?: string;
  region?: string;

  // Multiple addresses for each type
  sold_to_addresses: AddressEntry[];
  bill_to_addresses: AddressEntry[];
  ship_to_addresses: AddressEntry[];
  payer_to_addresses: AddressEntry[];

  // Address preferences
  default_address_setup: string;
  address_notes: string;
}

interface CustomerAddressManagerProps {
  customerData: CustomerAddress;
  onUpdate: (data: Partial<CustomerAddress>) => void;
  isEditing?: boolean;
}

const addressSetupOptions = [
  { value: 'standard', label: 'Standard Setup', description: 'Same address for all purposes' },
  { value: 'drop_ship', label: 'Drop Ship Setup', description: 'Ship directly to end customer' },
  { value: 'consignment', label: 'Consignment Setup', description: 'Ship to consignment location' },
  { value: 'multi_location', label: 'Multi-Location Setup', description: 'Different addresses for different purposes' }
];

export default function CustomerAddressManager({
  customerData,
  onUpdate,
  isEditing = false
}: CustomerAddressManagerProps) {
  const [copiedField, setCopiedField] = useState<string | null>(null);

  // Fetch countries for dropdown
  const { data: countriesList = [] } = useQuery<any[]>({
    queryKey: ['/api/master-data/countries'],
    queryFn: async () => {
      const response = await apiRequest('/api/master-data/countries');
      return await response.json();
    },
    retry: 1,
  });

  // Fetch all states (we filter by country on the client side per address entry)
  const { data: allStatesList = [] } = useQuery<any[]>({
    queryKey: ['/api/master-data/states'],
    queryFn: async () => {
      const response = await apiRequest('/api/master-data/states');
      return await response.json();
    },
    retry: 1,
  });

  // Helper to get states for a specific country name
  const getStatesForCountry = (countryName: string) => {
    if (!countryName) return [];
    const country = (countriesList as any[]).find(
      (c: any) => c.name === countryName || c.code === countryName
    );
    if (!country) return [];
    return (allStatesList as any[]).filter((s: any) => (s.countryId || s.country_id) === country.id);
  };

  // Use ref to track temp counter to avoid re-renders
  const tempCounterRef = React.useRef<number>(0);

  // Helper function to generate a unique temporary address number for preview
  // This shows in the UI immediately when adding an address
  // Format: ADDR-TEMP-XXXXXX (temporary) or uses existing if address is already saved
  // Use useMemo with stable reference to avoid re-creation on every render
  const generateTempAddressNumber = React.useCallback((): string => {
    // Increment the ref counter - this ensures unique numbers without reading customerData
    tempCounterRef.current += 1;

    // Generate next temporary number using timestamp and counter for uniqueness
    const timestamp = Date.now().toString().slice(-6);
    const counter = tempCounterRef.current.toString().padStart(4, '0');
    return `ADDR-TEMP-${timestamp}-${counter}`;
  }, []); // No dependencies - uses only ref which doesn't trigger re-renders

  // Helper function to strip address_number from address data
  // This ensures address_number is NEVER sent to the API - it's auto-generated by the database
  // Temporary address numbers (ADDR-TEMP-*) should also be stripped
  const stripAddressNumber = (address: Partial<AddressEntry>): Partial<AddressEntry> => {
    const { address_number, ...addressWithoutNumber } = address;
    return addressWithoutNumber;
  };

  // Helper function to strip address_number from an array of addresses
  const stripAddressNumbers = (addresses: AddressEntry[]): Partial<AddressEntry>[] => {
    return addresses.map(addr => stripAddressNumber(addr));
  };

  // Helper function to create a new address entry with temporary address number for preview
  // The temporary address_number will be visible in UI immediately
  // When saved to database, the database will generate the real address_number
  const createNewAddress = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to'): AddressEntry => {
    const tempAddressNumber = generateTempAddressNumber();

    return {
      id: `${type}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      address_number: tempAddressNumber, // Temporary preview address number - visible immediately
      address_name: '',
      contact_person: '',
      company_name: '',
      address_line_1: '',
      address_line_2: '',
      city: '',
      state: '',
      country: '',
      postal_code: '',
      region: '',
      phone: '',
      email: '',
      is_primary: false,
      notes: ''
    };
  };

  // Helper function to add a new address
  const addAddress = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to') => {
    const newAddress = createNewAddress(type);
    // address_number is intentionally NOT set - it will be auto-generated by database when saved
    // When updating state, we don't include address_number for new addresses
    const currentAddresses = customerData[`${type}_addresses`] || [];

    // Check if we're already adding this address (prevent duplicate adds)
    const addressExists = currentAddresses.some(addr => addr.id === newAddress.id);
    if (addressExists) {
      return; // Address already exists, don't add again
    }

    const updatedAddresses = [...currentAddresses, newAddress];

    // Only update if addresses array actually changed (length increased)
    if (updatedAddresses.length !== currentAddresses.length) {
      onUpdate({
        [`${type}_addresses`]: updatedAddresses
      });

      // Scroll to the newly added address after a brief delay to ensure it's rendered
      // Use requestAnimationFrame to ensure DOM is updated first
      requestAnimationFrame(() => {
        setTimeout(() => {
          const addressElement = document.getElementById(`address-${newAddress.id}`);
          if (addressElement) {
            addressElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
            // Highlight the new address briefly
            addressElement.classList.add('ring-2', 'ring-blue-400', 'ring-opacity-50');
            setTimeout(() => {
              addressElement.classList.remove('ring-2', 'ring-blue-400', 'ring-opacity-50');
            }, 2000);
          }
        }, 100);
      });
    }
  };

  // Helper function to remove an address
  const removeAddress = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to', addressId: string) => {
    const currentAddresses = customerData[`${type}_addresses`] || [];
    const updatedAddresses = currentAddresses.filter(addr => addr.id !== addressId);

    onUpdate({
      [`${type}_addresses`]: updatedAddresses
    });
  };

  // Helper function to update an address
  const updateAddress = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to', addressId: string, updates: Partial<AddressEntry>) => {
    // Prevent updating address_number (it's auto-generated and read-only)
    // Strip address_number from updates if it somehow exists
    const safeUpdates = stripAddressNumber(updates);

    // If updates are empty after stripping, don't proceed
    if (!safeUpdates || Object.keys(safeUpdates).length === 0) {
      return;
    }

    const currentAddresses = customerData[`${type}_addresses`] || [];
    const addressIndex = currentAddresses.findIndex(addr => addr.id === addressId);

    // If address not found, don't proceed
    if (addressIndex === -1) {
      return;
    }

    const currentAddress = currentAddresses[addressIndex];

    // Check if any of the updates actually change the values
    let hasChanges = false;
    for (const key in safeUpdates) {
      if (safeUpdates.hasOwnProperty(key)) {
        const newValue = safeUpdates[key as keyof AddressEntry];
        const currentValue = currentAddress[key as keyof AddressEntry];
        if (newValue !== currentValue) {
          hasChanges = true;
          break;
        }
      }
    }

    // If no actual changes, don't update
    if (!hasChanges) {
      return;
    }

    const updatedAddresses = currentAddresses.map(addr => {
      if (addr.id === addressId) {
        // Preserve existing address_number from API, but don't allow manual updates
        const { address_number: existingNumber } = addr;
        const updated = { ...addr, ...safeUpdates };
        // Keep existing address_number if it exists (from database)
        if (existingNumber) {
          updated.address_number = existingNumber;
        }
        return updated;
      }
      return addr;
    });

    onUpdate({
      [`${type}_addresses`]: updatedAddresses
    });
  };

  // Helper function to set primary address
  const setPrimaryAddress = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to', addressId: string) => {
    const currentAddresses = customerData[`${type}_addresses`] || [];
    const updatedAddresses = currentAddresses.map(addr => ({
      ...addr,
      is_primary: addr.id === addressId
    }));

    onUpdate({
      [`${type}_addresses`]: updatedAddresses
    });
  };

  // Helper function to copy address from main to a specific type
  // In SAP, the "main" address is the primary Sold To address
  const copyMainAddressToType = (type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to') => {
    // Find the primary Sold To address - this is the "main" address in SAP
    const soldToAddresses = customerData.sold_to_addresses || [];
    const primarySoldTo = soldToAddresses.find(addr => addr.is_primary) || soldToAddresses[0];

    // If no Sold To address exists, try to use the customer's general data fields as fallback
    const mainAddress = primarySoldTo ? {
      address_name: `${primarySoldTo.address_name} (Copy)` || 'Main Address (Copy)',
      contact_person: primarySoldTo.contact_person || '',
      company_name: primarySoldTo.company_name || '',
      address_line_1: primarySoldTo.address_line_1 || '',
      address_line_2: primarySoldTo.address_line_2 || '',
      city: primarySoldTo.city || '',
      state: primarySoldTo.state || '',
      country: primarySoldTo.country || '',
      postal_code: primarySoldTo.postal_code || '',
      region: primarySoldTo.region || '',
      phone: primarySoldTo.phone || '',
      email: primarySoldTo.email || '',
      is_primary: true,
      notes: `Copied from ${primarySoldTo.address_name || 'main Sold To address'}`
    } : {
      // Fallback: use customer general data if no Sold To address exists
      address_name: 'Main Address',
      contact_person: '',
      company_name: '',
      address_line_1: customerData.address || '',
      address_line_2: '',
      city: customerData.city || '',
      state: customerData.state || '',
      country: customerData.country || '',
      postal_code: customerData.postal_code || '',
      region: '',
      phone: customerData.phone || '',
      email: customerData.email || '',
      is_primary: true,
      notes: 'Copied from customer general data'
    };

    const newAddress = createNewAddress(type);
    // Use the temporary address_number from createNewAddress, and copy other fields from main
    // The temporary number will be visible immediately in the UI
    const updatedAddress = { ...newAddress, ...mainAddress };

    const currentAddresses = customerData[`${type}_addresses`] || [];
    const updatedAddresses = [...currentAddresses, updatedAddress];

    onUpdate({
      [`${type}_addresses`]: updatedAddresses
    });
  };

  // Component for rendering a single address entry
  const renderAddressEntry = (
    address: AddressEntry,
    type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to',
    index: number
  ) => (
    <Card
      key={address.id}
      id={`address-${address.id}`}
      className="border-l-4 border-l-blue-500 transition-all duration-300"
    >
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Badge variant={address.is_primary ? "default" : "secondary"}>
              {address.is_primary ? "Primary" : `Address ${index + 1}`}
            </Badge>
            {/* Always show address number badge - even for new addresses */}
            <Badge
              variant={
                address.address_number?.startsWith('ADDR-TEMP-')
                  ? "secondary"
                  : address.address_number
                    ? "outline"
                    : "secondary"
              }
              className="font-mono text-xs"
              title={
                address.address_number?.startsWith('ADDR-TEMP-')
                  ? "Temporary preview - will be replaced when saved"
                  : address.address_number
                    ? "Auto-generated address number"
                    : "Address number will be generated when saved"
              }
            >
              {address.address_number || 'Pending...'}
              {address.address_number?.startsWith('ADDR-TEMP-') && (
                <span className="ml-1 text-xs opacity-70">(Preview)</span>
              )}
            </Badge>
            {address.address_name && (
              <span className="font-medium">{address.address_name}</span>
            )}
          </div>
          <div className="flex gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => setPrimaryAddress(type, address.id)}
              disabled={!isEditing || address.is_primary}
            >
              Set Primary
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => removeAddress(type, address.id)}
              disabled={!isEditing}
              className="text-red-600 hover:text-red-700"
            >
              <Trash2 className="h-3 w-3" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Address Number - Read-only, auto-generated, NEVER editable */}
        {/* CRITICAL: Always show the address number field for ALL addresses - NO CONDITIONALS */}
        <div className="w-full" style={{ display: 'block', visibility: 'visible' }}>
          <Label className="flex items-center gap-2" htmlFor={`address-number-${address.id}`}>
            Address Number
            <span className="text-xs text-muted-foreground font-normal">(Auto-generated)</span>
          </Label>
          <Input
            id={`address-number-${address.id}`}
            value={address.address_number || 'Pending generation...'}
            disabled={true}
            readOnly={true}
            className={`bg-muted cursor-not-allowed opacity-75 font-mono w-full ${address.address_number?.startsWith('ADDR-TEMP-') ? 'border-yellow-300' : ''
              }`}
            style={{ display: 'block', visibility: 'visible' }}
            title={
              address.address_number?.startsWith('ADDR-TEMP-')
                ? "Temporary preview address number - will be replaced with real number when saved"
                : address.address_number
                  ? "Auto-generated unique address number - cannot be modified"
                  : "Address number will be auto-generated when saved to database"
            }
            tabIndex={-1}
            onKeyDown={(e) => {
              e.preventDefault(); // Prevent any keyboard input
            }}
            onFocus={(e) => {
              e.target.blur(); // Immediately remove focus if somehow focused
            }}
          />
          <p className="text-xs text-muted-foreground mt-1" style={{ display: 'block', visibility: 'visible' }}>
            {address.address_number?.startsWith('ADDR-TEMP-')
              ? 'Preview number - will be replaced with auto-generated number when saved'
              : address.address_number
                ? 'Auto-generated by database - not editable'
                : 'Will be auto-generated when address is saved'}
          </p>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <Label>Address Name <span className="text-red-500">*</span></Label>
            <Input
              value={address.address_name}
              onChange={(e) => updateAddress(type, address.id, { address_name: e.target.value })}
              placeholder="e.g., Main Office, Warehouse"
              disabled={!isEditing}
              required
            />
          </div>
          <div>
            <Label>Contact Person</Label>
            <Input
              value={address.contact_person}
              onChange={(e) => updateAddress(type, address.id, { contact_person: e.target.value })}
              placeholder="Contact person name"
              disabled={!isEditing}
            />
          </div>
        </div>

        <div>
          <Label>Company Name</Label>
          <Input
            value={address.company_name}
            onChange={(e) => updateAddress(type, address.id, { company_name: e.target.value })}
            placeholder="Company name (if different)"
            disabled={!isEditing}
          />
        </div>

        <div>
          <Label>Address Line 1 <span className="text-red-500">*</span></Label>
          <Input
            value={address.address_line_1}
            onChange={(e) => updateAddress(type, address.id, { address_line_1: e.target.value })}
            placeholder="Street address"
            disabled={!isEditing}
            required
          />
        </div>

        <div>
          <Label>Address Line 2</Label>
          <Input
            value={address.address_line_2}
            onChange={(e) => updateAddress(type, address.id, { address_line_2: e.target.value })}
            placeholder="Apartment, suite, unit, etc."
            disabled={!isEditing}
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <Label>City <span className="text-red-500">*</span></Label>
            <Input
              value={address.city}
              onChange={(e) => updateAddress(type, address.id, { city: e.target.value })}
              placeholder="City"
              disabled={!isEditing}
              required
            />
          </div>
          <div>
            <Label>Country <span className="text-red-500">*</span></Label>
            <Select
              value={address.country || ''}
              onValueChange={(value) => {
                updateAddress(type, address.id, { country: value, state: '' });
              }}
              disabled={!isEditing}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select country" />
              </SelectTrigger>
              <SelectContent>
                {countriesList.length === 0 ? (
                  <SelectItem value="no-countries" disabled>No countries available</SelectItem>
                ) : (
                  (countriesList as any[]).map((c: any) => (
                    <SelectItem key={c.id} value={c.code}>
                      {c.code} - {c.name}
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label>State/Province</Label>
            {(() => {
              const statesForCountry = getStatesForCountry(address.country);
              return (
                <Select
                  value={address.state || ''}
                  onValueChange={(value) => updateAddress(type, address.id, { state: value })}
                  disabled={!isEditing || !address.country}
                >
                  <SelectTrigger>
                    <SelectValue placeholder={address.country ? "Select state/province" : "Select country first"} />
                  </SelectTrigger>
                  <SelectContent>
                    {statesForCountry.length === 0 ? (
                      <SelectItem value="no-states" disabled>No states for this country</SelectItem>
                    ) : (
                      statesForCountry.map((s: any) => (
                        <SelectItem key={s.id} value={s.name || s.code}>
                          {s.code} - {s.name}
                        </SelectItem>
                      ))
                    )}
                  </SelectContent>
                </Select>
              );
            })()}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <Label>Postal Code</Label>
            <Input
              value={address.postal_code}
              onChange={(e) => updateAddress(type, address.id, { postal_code: e.target.value })}
              placeholder="Postal Code"
              disabled={!isEditing}
            />
          </div>
          <div>
            <Label>Region</Label>
            <Input
              value={address.region}
              onChange={(e) => updateAddress(type, address.id, { region: e.target.value })}
              placeholder="Region"
              disabled={!isEditing}
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <Label>Phone</Label>
            <Input
              value={address.phone}
              onChange={(e) => updateAddress(type, address.id, { phone: e.target.value })}
              placeholder="Phone number"
              disabled={!isEditing}
            />
          </div>
          <div>
            <Label>Email</Label>
            <Input
              value={address.email}
              onChange={(e) => updateAddress(type, address.id, { email: e.target.value })}
              placeholder="Email address"
              disabled={!isEditing}
            />
          </div>
        </div>

        <div>
          <Label>Notes</Label>
          <Textarea
            value={address.notes}
            onChange={(e) => updateAddress(type, address.id, { notes: e.target.value })}
            placeholder="Special instructions or notes..."
            disabled={!isEditing}
            rows={2}
          />
        </div>
      </CardContent>
    </Card>
  );

  // Component for rendering multiple addresses of a specific type
  const renderMultipleAddressSection = (
    title: string,
    icon: React.ReactNode,
    type: 'sold_to' | 'bill_to' | 'ship_to' | 'payer_to',
    badge?: string
  ) => {
    const addresses = customerData[`${type}_addresses`] || [];

    return (
      <Card className="w-full">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-lg">
              {icon}
              {title}
              {badge && <Badge variant="secondary">{badge}</Badge>}
            </CardTitle>
            {isEditing && (
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => addAddress(type)}
                  className="flex items-center gap-1"
                >
                  <Plus className="h-3 w-3" />
                  Add {title.replace(' Addresses', '')}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => copyMainAddressToType(type)}
                  className="flex items-center gap-1"
                >
                  <Copy className="h-3 w-3" />
                  Copy from Main
                </Button>
              </div>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {addresses.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <div className="text-sm">No {title.toLowerCase()} configured</div>
              {isEditing && (
                <div className="flex gap-2 justify-center">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => addAddress(type)}
                    className="mt-2"
                  >
                    Add First {title.replace(' Addresses', '')}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => copyMainAddressToType(type)}
                    className="mt-2"
                  >
                    Copy from Main
                  </Button>
                </div>
              )}
            </div>
          ) : (
            <div className="space-y-4">
              {addresses.map((address, index) => renderAddressEntry(address, type, index))}
            </div>
          )}
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="space-y-6">
      {/* Address Setup Configuration */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Building className="h-5 w-5" />
            Address Configuration
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="default_address_setup">Default Address Setup</Label>
            <Select
              value={customerData.default_address_setup}
              onValueChange={(value) => onUpdate({ default_address_setup: value })}
              disabled={!isEditing}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select address setup" />
              </SelectTrigger>
              <SelectContent>
                {addressSetupOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    <div>
                      <div className="font-medium">{option.label}</div>
                      <div className="text-sm text-muted-foreground">{option.description}</div>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label htmlFor="address_notes">Address Notes</Label>
            <Textarea
              id="address_notes"
              value={customerData.address_notes}
              onChange={(e) => onUpdate({ address_notes: e.target.value })}
              placeholder="Special instructions or notes about customer addresses..."
              disabled={!isEditing}
              rows={3}
            />
          </div>
        </CardContent>
      </Card>

      {/* Multiple Address Sections */}
      <div className="space-y-6">
        {renderMultipleAddressSection(
          "Sold To Addresses",
          <MapPin className="h-4 w-4" />,
          "sold_to",
          "Primary"
        )}

        {renderMultipleAddressSection(
          "Bill To Addresses",
          <CreditCard className="h-4 w-4" />,
          "bill_to"
        )}

        {renderMultipleAddressSection(
          "Ship To Addresses",
          <Truck className="h-4 w-4" />,
          "ship_to"
        )}

        {renderMultipleAddressSection(
          "Payer To Addresses",
          <Building className="h-4 w-4" />,
          "payer_to"
        )}
      </div>

      {/* Address Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Address Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-sm">
            <div>
              <div className="font-medium text-muted-foreground mb-2">Sold To ({customerData.sold_to_addresses?.length || 0})</div>
              {customerData.sold_to_addresses?.length > 0 ? (
                <div className="space-y-2">
                  {customerData.sold_to_addresses.map((addr, index) => (
                    <div key={addr.id} className="border-l-2 border-blue-500 pl-2">
                      <div className="font-medium text-xs">{addr.address_name || `Address ${index + 1}`}</div>
                      <div>{addr.address_line_1}</div>
                      <div>{addr.city}, {addr.state} {addr.postal_code}</div>
                      <div>{addr.country}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-muted-foreground italic">No addresses configured</div>
              )}
            </div>

            <div>
              <div className="font-medium text-muted-foreground mb-2">Bill To ({customerData.bill_to_addresses?.length || 0})</div>
              {customerData.bill_to_addresses?.length > 0 ? (
                <div className="space-y-2">
                  {customerData.bill_to_addresses.map((addr, index) => (
                    <div key={addr.id} className="border-l-2 border-green-500 pl-2">
                      <div className="font-medium text-xs">{addr.address_name || `Address ${index + 1}`}</div>
                      <div>{addr.address_line_1}</div>
                      <div>{addr.city}, {addr.state} {addr.postal_code}</div>
                      <div>{addr.country}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-muted-foreground italic">No addresses configured</div>
              )}
            </div>

            <div>
              <div className="font-medium text-muted-foreground mb-2">Ship To ({customerData.ship_to_addresses?.length || 0})</div>
              {customerData.ship_to_addresses?.length > 0 ? (
                <div className="space-y-2">
                  {customerData.ship_to_addresses.map((addr, index) => (
                    <div key={addr.id} className="border-l-2 border-orange-500 pl-2">
                      <div className="font-medium text-xs">{addr.address_name || `Address ${index + 1}`}</div>
                      <div>{addr.address_line_1}</div>
                      <div>{addr.city}, {addr.state} {addr.postal_code}</div>
                      <div>{addr.country}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-muted-foreground italic">No addresses configured</div>
              )}
            </div>

            <div>
              <div className="font-medium text-muted-foreground mb-2">Payer To ({customerData.payer_to_addresses?.length || 0})</div>
              {customerData.payer_to_addresses?.length > 0 ? (
                <div className="space-y-2">
                  {customerData.payer_to_addresses.map((addr, index) => (
                    <div key={addr.id} className="border-l-2 border-purple-500 pl-2">
                      <div className="font-medium text-xs">{addr.address_name || `Address ${index + 1}`}</div>
                      <div>{addr.address_line_1}</div>
                      <div>{addr.city}, {addr.state} {addr.postal_code}</div>
                      <div>{addr.country}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-muted-foreground italic">No addresses configured</div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
